//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IisAdmin.TestConsole.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAdministrationService")]
    public interface IAdministrationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrationService/AddUser", ReplyAction="http://tempuri.org/IAdministrationService/AddUserResponse")]
        bool AddUser(string username, string passwd, string fqdn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrationService/DelUser", ReplyAction="http://tempuri.org/IAdministrationService/DelUserResponse")]
        bool DelUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrationService/SetPasswd", ReplyAction="http://tempuri.org/IAdministrationService/SetPasswdResponse")]
        bool SetPasswd(string username, string passwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrationService/ResetPermissions", ReplyAction="http://tempuri.org/IAdministrationService/ResetPermissionsResponse")]
        bool ResetPermissions(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrationService/AddHost", ReplyAction="http://tempuri.org/IAdministrationService/AddHostResponse")]
        bool AddHost(string username, string fqdn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrationService/DelHost", ReplyAction="http://tempuri.org/IAdministrationService/DelHostResponse")]
        bool DelHost(string username, string fqdn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdministrationService/MkDir", ReplyAction="http://tempuri.org/IAdministrationService/MkDirResponse")]
        bool MkDir(string username, string directory);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdministrationServiceChannel : IisAdmin.TestConsole.ServiceReference1.IAdministrationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdministrationServiceClient : System.ServiceModel.ClientBase<IisAdmin.TestConsole.ServiceReference1.IAdministrationService>, IisAdmin.TestConsole.ServiceReference1.IAdministrationService {
        
        public AdministrationServiceClient() {
        }
        
        public AdministrationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdministrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdministrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddUser(string username, string passwd, string fqdn) {
            return base.Channel.AddUser(username, passwd, fqdn);
        }
        
        public bool DelUser(string username) {
            return base.Channel.DelUser(username);
        }
        
        public bool SetPasswd(string username, string passwd) {
            return base.Channel.SetPasswd(username, passwd);
        }
        
        public bool ResetPermissions(string username) {
            return base.Channel.ResetPermissions(username);
        }
        
        public bool AddHost(string username, string fqdn) {
            return base.Channel.AddHost(username, fqdn);
        }
        
        public bool DelHost(string username, string fqdn) {
            return base.Channel.DelHost(username, fqdn);
        }
        
        public bool MkDir(string username, string directory) {
            return base.Channel.MkDir(username, directory);
        }
    }
}
